name: prioritask
description: "Prioritask - A focused reminder app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_local_notifications: ^19.5.0
  get_it: ^9.2.0
  injectable: ^2.7.1+4
  google_fonts: ^7.0.2
  equatable: ^2.0.8
  intl: ^0.20.2
  flutter_timezone: ^5.0.1
  path_provider: ^2.1.5
  timezone: ^0.10.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1
  injectable_generator: ^2.4.2
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - lib/images/
